name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm ci

    - name: Run linting
      run: npm run lint

    - name: Run unit tests with coverage
      run: npm run test:unit -- --coverage

    - name: Start dev server
      run: npm run dev &

    - name: Wait for localhost to be ready
      run: npx wait-on http://localhost:5173

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test

    - name: Build for production
      run: npm run build
